### PR TITLE
Lock to working version of kvm-ioctls

### PR DESCRIPTION
**Pull request by c-densham**
Fixes the issue with `kvm-ioctls` using an incompatible version of `vmm-sys-util`.

### CODE REVIEW

**Comment by olivierpierre** [comment]
Looks good to me, I assume that the format errors we get are not particularly important?

**Comment by LaurentPool** [comment]
This seems to fix the issue when I try to install it. Thanks

**Review by LaurentPool — COMMENTED** [review]
Fixes the issue, will this merge to master?

**Comment by c-densham** [comment]
> Looks good to me, I assume that the format errors we get are not particularly important?

They shouldn't affect us. I'm not actually sure why they are failing as it's not a file that has been altered.

**Pull request merged**
