### PR TITLE
Change start address of kernel

### LINKED ISSUE #3: Relocate kernel start point

### PR DESCRIPTION
**Pull request by c-densham**
Relocate kernel start address to `0x200000`

### CODE REVIEW

**Review by olivierpierre — APPROVED** [review]
It looks good to me. I can see that the CI tests are passed, I assume that it's not only building the kernel but that they also include launching some sample application? If this work, I'd say that things are all good.

**Comment by c-densham** [comment]
> It looks good to me. I can see that the CI tests are passed, I assume that it's not only building the kernel but that they also include launching some sample application? If this work, I'd say that things are all good.

The CI runs tests configured in the Cargo test suite from the original devs. I have tested this manually with a `hello_world` program with the `--verbose` flag. This shows the location of the kernel:
```[0][INFO] Welcome to HermitCore-rs 0.3.43
[0][INFO] Kernel starts at 0x200000
[0][INFO] BSS starts at 0x421b00
[0][INFO] TLS starts at 0x3a1cc8 (size 176 Bytes)
[0][INFO] Total memory size: 64 MB
[0][INFO] Kernel region: [0x200000 - 0x600000]
[0][INFO] A pure Rust application is running on top of HermitCore!
[0][INFO] Heap: size 50 MB, start address 0x600000
[0][INFO] Heap is located at 0x600000 -- 0x3800000 (0 Bytes unmapped)
```

**Comment by olivierpierre** [comment]
Thanks for the log, I can see a problem: the kernel should be located starting at `0x200000` but also should fit entirely below `0x400000` which is the traditional location at which static application binaries are loaded. I can see two solutions:
- Somehow reduce the size of the kernel to have it fit below `0x400000` (I find it weird that it needs so much space compared to HermTux, maybe it's due to Rust's overhead)
- Load it in the classical area reserved for the kernel in Linux applications, i.e. starting at `0x800000000000`

**Comment by c-densham** [comment]
I'll look and see if it can be resized easily without causing any issues. If not then I can look at the second option.

**Comment by olivierpierre** [comment]
Sounds good, thanks Christopher

**Comment by c-densham** [comment]
Closed as unable to resize so will relocate to 0x800000000000 instead

**Comment by c-densham** [comment]
Giving a start address greater than `0x37dc000` causes an error during runtime.

Even though it states that the kernel starts at `0x37dc000` it looks like it is located starting at `0x3600000` so this is probably the actual maximum start address.

```[0][INFO] Welcome to HermitCore-rs 0.3.43
[0][INFO] Kernel starts at 0x37dc000
[0][INFO] BSS starts at 0x39fdb00
[0][INFO] TLS starts at 0x397dcc8 (size 176 Bytes)
[0][INFO] Total memory size: 64 MB
[0][INFO] Kernel region: [0x3600000 - 0x3a00000]
[0][INFO] A pure Rust application is running on top of HermitCore!
[0][INFO] Heap: size 2 MB, start address 0x3a00000
[0][INFO] Heap is located at 0x3a00000 -- 0x3c00000 (0 Bytes unmapped)
[0][INFO] 
[0][INFO] ===================== PHYSICAL MEMORY FREE LIST ======================
[0][INFO] 0x00000003C00000 - 0x00000004000000
[0][INFO] ======================================================================
[0][INFO] 
[0][INFO] 
[0][INFO] ================== KERNEL VIRTUAL MEMORY FREE LIST ===================
[0][INFO] 0x00000003C00000 - 0x00800000000000
[0][INFO] ======================================================================
```

**Comment by olivierpierre** [comment]
- Falling back on `0x3600000` looks normal to me, as the static memory is probably mapped using 2MB pages and it needs to be aligned on such page boundaries
- I see that the heap is starting at `0x3a00000` right after the kernel's static memory. Is this location hardcoded? It needs to be moved too

I let you investigate a bit, if things become too complex we can contact Stefan

**Comment by c-densham** [comment]
With the default amount of RAM (512MiB according to docs but log states 64 MB of memory) the heap starts directly after the kernel and usually goes up to `0x3800000`. e.g. with the original start address for the kernel `0x400000`:
```[0][INFO] Kernel starts at 0x400000
[0][INFO] BSS starts at 0x621b00
[0][INFO] TLS starts at 0x5a1cc8 (size 176 Bytes)
[0][INFO] Total memory size: 64 MB
[0][INFO] Kernel region: [0x400000 - 0x800000]
[0][INFO] A pure Rust application is running on top of HermitCore!
[0][INFO] Heap: size 48 MB, start address 0x800000
[0][INFO] Heap is located at 0x800000 -- 0x3800000 (0 Bytes unmapped)
```
But the start and end can vary depending on the amount of RAM allocated or when using the higher address locations for the kernel.

**Comment by c-densham** [comment]
It does appear to be aligning the memory regions to boundaries as you state. For addresses above `0x37dc000` it must be trying to align to the next page and we get core dumps e.g.:
```
Address 0x3c00000

0][INFO] Welcome to HermitCore-rs 0.3.43
[0][INFO] Kernel starts at 0x3c00000
[0][INFO] BSS starts at 0x3e21b00
[0][INFO] TLS starts at 0x3da1cc8 (size 176 Bytes)
[0][INFO] Total memory size: 64 MB
[0][INFO] Kernel region: [0x3c00000 - 0x4000000]

Dump state of CPU 0

Registers:
----------
kvm_regs { rax: 64635616, rbx: 62913840, rcx: 65111648, rdx: 64635616, rsi: 65122608, rdi: 62913792, rsp: 62913760, rbp: 2240512, r8: 0, r9: 7, r10: 0, r11: 0, r12: 0, r13: 0, r14: 64635616, r15: 0, rip: 64520685, rflags: 65538 }kvm_sregs { cs: kvm_segment { base: 0, limit: 4294967295, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 1, avl: 0, unusable: 0, padding: 0 }, ds: kvm_segment { base: 0, limit: 4294967295, selector: 16, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, es: kvm_segment { base: 0, limit: 4294967295, selector: 16, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, fs: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gs: kvm_segment { base: 65150080, limit: 65535, selector: 0, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, ss: kvm_segment { base: 0, limit: 4294967295, selector: 16, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }, tr: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 11, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, ldt: kvm_segment { base: 0, limit: 65535, selector: 0, type_: 2, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }, gdt: kvm_dtable { base: 4096, limit: 23, padding: [0, 0, 0] }, idt: kvm_dtable { base: 0, limit: 65535, padding: [0, 0, 0] }, cr0: 2147549243, cr2: 0, cr3: 65536, cr4: 329312, cr8: 0, efer: 3329, apic_base: 4276095232, interrupt_bitmap: [0, 0, 0, 0] }
Segment registers:
------------------
register  selector  base              limit     type  p dpl db s l g avl
cs        kvm_segment { base: 0, limit: 4294967295, selector: 8, type_: 11, present: 1, dpl: 0, db: 0, s: 1, l: 1, g: 1, avl: 0, unusable: 0, padding: 0 }
ss        kvm_segment { base: 0, limit: 4294967295, selector: 16, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }
ds        kvm_segment { base: 0, limit: 4294967295, selector: 16, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }
es        kvm_segment { base: 0, limit: 4294967295, selector: 16, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 1, avl: 0, unusable: 0, padding: 0 }
fs        kvm_segment { base: 0, limit: 65535, selector: 0, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }
gs        kvm_segment { base: 65150080, limit: 65535, selector: 0, type_: 3, present: 1, dpl: 0, db: 0, s: 1, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }
tr        kvm_segment { base: 0, limit: 65535, selector: 0, type_: 11, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }
ldt       kvm_segment { base: 0, limit: 65535, selector: 0, type_: 2, present: 1, dpl: 0, db: 0, s: 0, l: 0, g: 0, avl: 0, unusable: 0, padding: 0 }
gdt                 kvm_dtable { base: 4096, limit: 23, padding: [0, 0, 0] }
idt                 kvm_dtable { base: 0, limit: 65535, padding: [0, 0, 0] }


APIC:
-----
efer: 0000000000000d01  apic base: 00000000fee00900
```

If we go even higher to say `0x4000000` and beyond then we get panics:
```
[2020-11-18T19:01:23Z ERROR uhyvelib::vm] Guest memory size isn't large enough
thread 'main' panicked at 'Unabled to load the kernel: NotEnoughMemory', src/bin/uhyve.rs:183:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is all with the default RAM.

**Comment by olivierpierre** [comment]
Can you have a look at what triggers the panic `'Unabled to load the kernel: NotEnoughMemory'`?

**Comment by c-densham** [comment]
Apologies, the way Github had handled the markdown truncated the first line:
```
[2020-11-18T19:01:23Z ERROR uhyvelib::vm] Guest memory size isn't large enough
```
Have tested with larger RAM and it works. It looks like the default RAM **is** only 64 M. I can go up to about 1 G on this machine, will try and find the acceptable range of addresses.

**Comment by olivierpierre** [comment]
Cool, thanks!

**Pull request closed without merging**
